version: "3.3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  similar-product-service:
    build: similar-product/
    container_name: similar-product-service
    ports:
      - "5000:5000"
    environment:
      - SPRING_APPLICATION_JSON={"server.port":5000}
    depends_on:
      - simulado
  influxdb:
    image: influxdb:1.8.2
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./shared/grafana:/etc/grafana/provisioning/
  simulado:
    image : ldabiralai/simulado:latest
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
  k6:
    image: loadimpact/k6:0.28.0
    ports:
      - "6565:6565"
    volumes:
      - ./shared/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
